project:
  type: website
  output-dir: docs

website:
  title: "Kyrylo Koltunov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Text Analysis
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: sandstone
    css: styles.css





